post_install() {
	getent group ioslaves &>/dev/null || groupadd --system -g 290 ioslaves
	getent passwd ioslaves &>/dev/null || useradd --system --uid 290 --gid ioslaves --home-dir /var/ioslaves --shell /bin/false ioslaves
	chown -R ioslaves:ioslaves /var/ioslaves /etc/ioslavesd/keys
}

post_upgrade() {
	post_install
	systemctl daemon-reload
	systemctl restart ioslavesd
}

pre_remove() {
	systemctl stop ioslavesd
}
post_remove() {
	userdel ioslaves || true
	groupdel ioslaves || true
}
