post_install() {
	groupadd --system -g 290 ioslaves || true
	useradd --system --uid 290 --gid ioslaves --home-dir /var/ioslaves --shell /bin/false ioslaves || true
	chown -R ioslaves:ioslaves /var/ioslaves /etc/ioslavesd
}

post_upgrade() {
	post_install
	systemctl daemon-reload
	systemctl restart ioslavesd
}

pre_remove() {
	systemctl stop ioslavesd
}
post_remove() {
	userdel ioslaves || true
	groupdel ioslaves || true
}
